=== AlexAbak/geneticist/xml/geneticist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://deneblingvo.org/xsd/geneticist/1.0" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gen="http://deneblingvo.org/xsd/geneticist/1.0">

    <element name="geneticist" type="gen:geneticist"></element>

    <complexType name="geneticist">
    	<sequence>
    		<element name="operators" type="gen:operators"></element>
    		<element name="connections" type="gen:connections"></element>
    	</sequence>
    </complexType>

    <complexType name="operators">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="operator" type="gen:operator"></element>
    	</sequence>
    </complexType>

    <complexType name="operator">
    	<sequence>
    		<element name="parameters" type="gen:parameters"></element>
    		<element name="output" type="gen:type"></element>
    		<element name="format" type="string"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="parameters">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="parameter" type="gen:parameter"></element>
    	</sequence>
    </complexType>

    <complexType name="parameter">
    	<sequence>
    		<element name="type" type="gen:type"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="connections">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="connection" type="gen:connection"></element>
    	</sequence>
    </complexType>

    <complexType name="connection">
    	<sequence>
    		<element name="type" type="gen:type"></element>
    		<element name="types" type="gen:types"></element>
    	</sequence>
    </complexType>

    <complexType name="types">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="type" type="gen:type"></element>
    	</sequence>
    </complexType>

    <complexType name="type">
    	<attribute name="kind" type="gen:kind" use="required"></attribute>
    	<attribute name="var" type="boolean"></attribute>
    	<attribute name="ref" type="string"></attribute>
    </complexType>

    <simpleType name="kind">
    	<restriction base="string">
    		<enumeration value="void"></enumeration>
    		<enumeration value="byte"></enumeration>
    		<enumeration value="short"></enumeration>
    		<enumeration value="int"></enumeration>
    		<enumeration value="long"></enumeration>
    		<enumeration value="char"></enumeration>
    		<enumeration value="integer"></enumeration>
    		<enumeration value="float"></enumeration>
    		<enumeration value="double"></enumeration>
    		<enumeration value="floating"></enumeration>
    		<enumeration value="boolean"></enumeration>
    		<enumeration value="String"></enumeration>
    		<enumeration value="all"></enumeration>
    		<enumeration value="ref"></enumeration>
    	</restriction>
    </simpleType>

</schema>

=== AlexAbak/geneticist/xml/geneticist.xml
<?xml version="1.0" encoding="UTF-8"?>
<gen:geneticist xmlns:gen="http://deneblingvo.org/xsd/geneticist/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://deneblingvo.org/xsd/geneticist/1.0 geneticist.xsd ">
  <gen:operators>
    <gen:operator name="assignment" output="void">
    	<gen:parameters >
    		<gen:parameter name="first" type="all" ></gen:parameter>
    		<gen:parameter name="second" type="ref" ref="first"
    			isVar="true" /></gen:parameters>
    	<gen:format>{$second} = {$first};
</gen:format>
    </gen:operator>

    <gen:operator name="equal" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="boolean" />
    	</gen:parameters>
    	<gen:format>({$first} == {$second})</gen:format>
    </gen:operator>
    <gen:operator name="notEqual" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="boolean" />
    	</gen:parameters>
    	<gen:format>({$first} != {$second})</gen:format>
    </gen:operator>

    <gen:operator name="not" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    	</gen:parameters>
    	<gen:format>(!{$first})</gen:format>
    </gen:operator>

    <gen:operator name="and" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="boolean" />
    	</gen:parameters>
    	<gen:format>({$first} &amp; {$second})</gen:format>
    </gen:operator>
    <gen:operator name="or" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="boolean" />
    	</gen:parameters>
    	<gen:format>({$first} | {$second})</gen:format>
    </gen:operator>
    <gen:operator name="andLazy" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="boolean" />
    	</gen:parameters>
    	<gen:format>({$first} &amp;&amp; {$second})</gen:format>
    </gen:operator>
    <gen:operator name="orLazy" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="boolean" />
    	</gen:parameters>
    	<gen:format>({$first} || {$second})</gen:format>
    </gen:operator>

    <gen:operator name="if" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="boolean" />
    		<gen:parameter name="third" type="boolean" />
    	</gen:parameters>
    	<gen:format>({$first} ? {$second} : {$third})</gen:format>
    </gen:operator>

    <gen:operator name="positive" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(+{$first})</gen:format>
    </gen:operator>
    <gen:operator name="negative" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(-{$first})</gen:format>
    </gen:operator>

    <gen:operator name="less" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} &lt; {$second})</gen:format>
    </gen:operator>
    <gen:operator name="lessOrEqual" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} &lt;= {$second})</gen:format>
    </gen:operator>
    <gen:operator name="more" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} &gt; {$second})</gen:format>
    </gen:operator>
    <gen:operator name="moreOrEqual" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} &gt;= {$second})</gen:format>
    </gen:operator>
    <gen:operator name="equal" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} == {$second})</gen:format>
    </gen:operator>
    <gen:operator name="notEqual" output="boolean">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} != {$second})</gen:format>
    </gen:operator>

    <gen:operator name="addition" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} + {$second})</gen:format>
    </gen:operator>
    <gen:operator name="subtraction" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} - {$second})</gen:format>
    </gen:operator>
    <gen:operator name="multiplication" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} * {$second})</gen:format>
    </gen:operator>
    <gen:operator name="division" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} / {$second})</gen:format>
    </gen:operator>
    <gen:operator name="remainder" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} % {$second})</gen:format>
    </gen:operator>

    <gen:operator name="prefixIncrement" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(++{$first})</gen:format>
    </gen:operator>
    <gen:operator name="prefixDecrement" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(--{$first})</gen:format>
    </gen:operator>
    <gen:operator name="postfixIncrement" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first}++)</gen:format>
    </gen:operator>
    <gen:operator name="postfixDecrement" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first}--)</gen:format>
    </gen:operator>

    <gen:operator name="shiftLeft" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(&lt;&lt;{$first})</gen:format>
    </gen:operator>
    <gen:operator name="shiftRight" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(&gt;&gt;{$first})</gen:format>
    </gen:operator>
    <gen:operator name="shiftRightSigned" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(&gt;&gt;&gt;{$first})</gen:format>
    </gen:operator>

    <gen:operator name="not" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    	</gen:parameters>
    	<gen:format>(~{$first})</gen:format>
    </gen:operator>

    <gen:operator name="and" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} &amp; {$second})</gen:format>
    </gen:operator>
    <gen:operator name="or" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="integer" />
    		<gen:parameter name="second" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} | {$second})</gen:format>
    </gen:operator>

    <gen:operator name="if" output="integer">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="integer" />
    		<gen:parameter name="third" type="integer" />
    	</gen:parameters>
    	<gen:format>({$first} ? {$second} : {$third})</gen:format>
    </gen:operator>

    <gen:operator name="if" output="void">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="void" />
    		<gen:parameter name="third" type="void" />
    	</gen:parameters>
    	<gen:format>if {$first} {
  {$second}
} else {
  {$third}
}
</gen:format>
    </gen:operator>
    <gen:operator name="while" output="void">
    	<gen:parameters>
    		<gen:parameter name="first" type="boolean" />
    		<gen:parameter name="second" type="void" />
    	</gen:parameters>
    	<gen:format>while {$first} {
  {$second}
}
</gen:format>
    </gen:operator>
    
  </gen:operators>
</gen:geneticist>
